name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - name: Run Jest coverage
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run cover
      - name: Run Lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
